URP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from photo.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls', namespace='photo')),

    # Обслуживание медиа-файлов, если DEBUG = False
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

handler404 = custom_404_view

# Обслуживание статических и медиа-файлов только при DEBUG = True
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'photo'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_directory/', views.create_directory, name='create_directory'),
    path('delete_directory/<path:directory>/', views.delete_directory, name='delete_directory'),

    # 🔹 Универсальный маршрут для переименования папки
    path('edit_directory/<path:current_directory>/<path:directory>/', views.edit_directory, name='edit_directory'),
    path('edit_directory/<path:directory>/', views.edit_directory, name='edit_directory_root'),  # ⬅ Для корневых папок

    path('upload_photo/<path:directory>/', views.upload_photo, name='upload_photo'),

    # Удаление фото и видео
    path('delete_media/<path:media_path>/', views.delete_media, name='delete_media'),

    # Авторизация
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

photo/models.py
from django.db import models

# Create your models here.

photo/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import os
from django.conf import settings
from urllib.parse import unquote
from django.contrib.auth.decorators import login_required
from urllib.parse import unquote
from datetime import datetime
from django.conf import settings
import shutil
from django.http import JsonResponse
import logging
import json

MEDIA_ROOT = settings.MEDIA_ROOT

def index(request):
    current_directory = request.GET.get('directory', '').lstrip('/')
    current_directory_path = os.path.normpath(os.path.join(MEDIA_ROOT, current_directory))

    # Проверка безопасности пути
    if not current_directory_path.startswith(MEDIA_ROOT):
        return HttpResponse("Invalid directory path", status=400)

    # Создание директории, если её нет
    if not os.path.exists(current_directory_path):
        os.makedirs(current_directory_path)

    # Получаем список директорий
    directories = [
        {
            'name': d,
            'creation_time': os.stat(os.path.join(current_directory_path, d)).st_ctime,
            'creation_date': datetime.fromtimestamp(os.stat(os.path.join(current_directory_path, d)).st_ctime).strftime('%d.%m.%Y %H:%M')
        }
        for d in os.listdir(current_directory_path)
        if os.path.isdir(os.path.join(current_directory_path, d))
    ]

    # Сортируем папки по дате создания (от новых к старым)
    directories = sorted(directories, key=lambda x: x['creation_time'], reverse=True)

    # Разделяем фото и видео
    image_extensions = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp'}
    video_extensions = {'.mp4', '.webm', '.mov', '.avi', '.mkv'}

    photos = []
    videos = []

    for file in os.listdir(current_directory_path):
        file_path = os.path.join(current_directory_path, file)
        if os.path.isfile(file_path):
            ext = os.path.splitext(file)[1].lower()
            if ext in image_extensions:
                photos.append(file)
            elif ext in video_extensions:
                videos.append(file)

    return render(request, 'photo/index.html', {
        'current_directory': current_directory,
        'directories': directories,
        'photos': photos,
        'videos': videos,  # Передаем видео отдельно
        'MEDIA_URL': settings.MEDIA_URL,
    })

@login_required
@csrf_exempt
def create_directory(request):
    if request.method == 'POST':
        current_directory = request.POST.get('current_directory', '').lstrip('/')
        directory_name = request.POST.get('directory_name')
        
        # путь для новой папки
        new_dir_path = os.path.normpath(os.path.join(MEDIA_ROOT, current_directory, directory_name))
        if not new_dir_path.startswith(MEDIA_ROOT):
            return HttpResponse("Invalid directory path", status=400)

        if not os.path.exists(new_dir_path):
            os.makedirs(new_dir_path)

        return redirect(f"{reverse('photo:index')}?directory={current_directory}")

@login_required
@csrf_exempt
def delete_directory(request, directory):
    if request.method == 'POST':
        directory = unquote(directory).strip('/')
        dir_path = os.path.normpath(os.path.join(MEDIA_ROOT, directory))

        if not dir_path.startswith(MEDIA_ROOT):
            return JsonResponse({"error": "Ошибка: путь выходит за пределы MEDIA_ROOT"}, status=400)

        if os.path.exists(dir_path) and os.path.isdir(dir_path):
            shutil.rmtree(dir_path)

        return JsonResponse({"success": True})

logger = logging.getLogger(__name__)

@login_required
@csrf_exempt
def upload_photo(request, directory):
    directory = unquote(directory)  # Декодируем путь
    if directory == 'root':
        directory = ''

    if request.method == 'POST' and request.FILES.getlist('photos'):
        current_directory = directory.lstrip('/')
        files = request.FILES.getlist('photos')
        directory_path = os.path.join(MEDIA_ROOT, current_directory)

        if not os.path.exists(directory_path):
            os.makedirs(directory_path)

        for photo in files:
            file_path = os.path.join(directory_path, photo.name)
            with open(file_path, 'wb') as f:
                for chunk in photo.chunks():
                    f.write(chunk)

        return redirect(f"{reverse('photo:index')}?directory={directory}")


@login_required
@csrf_exempt
def edit_directory(request, directory, current_directory=""):
    """Переименование папки с поддержкой вложенных и корневых директорий"""
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            new_name = data.get("new_name", "").strip()

            if not new_name:
                return JsonResponse({"error": "Новое имя не может быть пустым"}, status=400)

            # 🔹 Определяем родительский каталог
            current_directory = unquote(current_directory or "").strip("/")
            directory = unquote(directory).strip("/")

            # 🛠 Формируем пути
            current_path = os.path.normpath(os.path.join(settings.MEDIA_ROOT, current_directory, directory))
            new_path = os.path.normpath(os.path.join(settings.MEDIA_ROOT, current_directory, new_name))

            # 🔒 Проверки безопасности
            if not current_path.startswith(settings.MEDIA_ROOT) or not new_path.startswith(settings.MEDIA_ROOT):
                return JsonResponse({"error": "Некорректный путь"}, status=400)

            if not os.path.exists(current_path):
                return JsonResponse({"error": "Исходная папка не найдена"}, status=404)

            if os.path.exists(new_path):
                return JsonResponse({"error": "Папка с таким именем уже существует"}, status=400)

            print(f"CURRENT_PATH: {current_path}")
            print(f"NEW_PATH: {new_path}")

            os.rename(current_path, new_path)

            return JsonResponse({"success": True, "new_name": new_name})
        except json.JSONDecodeError:
            return JsonResponse({"error": "Ошибка обработки запроса"}, status=400)


@login_required
@csrf_exempt
def delete_media(request, media_path):
    """Удаление фото или видео"""
    media_path = unquote(media_path).strip('/')
    full_media_path = os.path.normpath(os.path.join(MEDIA_ROOT, media_path))

    if not full_media_path.startswith(MEDIA_ROOT):
        return JsonResponse({"error": "Ошибка: путь выходит за пределы MEDIA_ROOT"}, status=400)

    if os.path.exists(full_media_path) and os.path.isfile(full_media_path):
        os.remove(full_media_path)
        return JsonResponse({"success": True})

    return JsonResponse({"error": "Файл не найден"}, status=404)


def custom_404_view(request, exception):
    return render(request, 'error/404.html', status=404)

photo/templates/photo/index.html
{% load custom_filters %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Photo Manager</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'urp/css/style.css' %}"> 
</head>

<body class="container-fluid my-4">
    {% if not current_directory %}
        <div class="position-relative mb-4">
            <!-- Заголовок -->
            <h1 class="Name-page text-center">Наши фотографии</h1>

            <!-- Блок с кнопкой "Войти" или "Выйти" -->
            {% if user.is_authenticated %}
                <a href="{% url 'photo:logout' %}" class="position-absolute top-0 end-0">
                    <img src="{% static 'icons/logout.png' %}" alt="Выйти" style="width: 30px; height: 30px; margin-right: 8px;">
                    </a>
            {% else %}
                <a href="{% url 'photo:login' %}" class="position-absolute top-0 end-0">
                    <img src="{% static 'icons/login.png' %}" alt="Войти" style="width: 30px; height: 30px; margin-right: 8px;">
                    </a>
            {% endif %}
        </div>
    {% endif %}
    
    <div class="d-flex justify-content-between align-items-center mb-4">
        <!-- Кнопка "Назад" -->
        {% if current_directory %}
            <a href="?directory={{ current_directory|default:''|dirname|urlencode }}" class="btn btn-light">
                <img src="{% static 'icons/arrow-left.png' %}" alt="Назад" style="width: 20px; height: 20px; margin-right: 8px;">
                Назад
            </a>

            <!-- Иконки справа -->
            <div class="d-flex align-items-center">
                <!-- "Домой" -->
                <a href="{% url 'photo:index' %}" class="btn">
                    <img src="{% static 'icons/home.png' %}" alt="Домой" style="width: 30px; height: 30px;">
                </a>
        
                <!-- Войти / Выйти -->
                {% if user.is_authenticated %}
                    <a href="{% url 'photo:logout' %}" class="btn">
                        <img src="{% static 'icons/logout.png' %}" alt="Выйти" style="width: 30px; height: 30px;">
                    </a>
                {% else %}
                    <a href="{% url 'photo:login' %}" class="btn">
                        <img src="{% static 'icons/login.png' %}" alt="Войти" style="width: 30px; height: 30px;">
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <!-- Форма для создания новой папки -->
    {% if user.is_authenticated %}
        <form action="{% url 'photo:create_directory' %}" method="POST" class="mb-4">
            {% csrf_token %}
            <input type="hidden" name="current_directory" value="{{ current_directory }}">
            <div class="input-group has-validation">
                <input type="text" id="new_directory" name="directory_name" class="form-control"
                    placeholder="Введите название новой папки" required oninput="toggleCreateButton()">
                <button type="submit" id="createButton" class="btn btn-secondary btn-create" disabled>Создать папку</button>
            </div>
        </form>
    
    {% endif %}

    <!-- Форма загрузки фотографий -->
    {% if user.is_authenticated %}
        <form action="{% url 'photo:upload_photo' current_directory|default:'root'|urlencode %}" method="POST" enctype="multipart/form-data" class="mb-4">
            {% csrf_token %}
            <div class="upload-container">
                <input type="file" id="photos" name="photos" class="form-control" accept="image/*" multiple required onchange="toggleUploadButton(this)">
                <button type="submit" id="uploadButton" class="btn btn-secondary btn-load" disabled>Загрузить</button>
            </div>
        </form>
    {% endif %}

    <!-- Название текущей директории -->
    {% if current_directory %}
        <h2 class="mb-3 text-center">{{ current_directory }}</h2>
    {% comment %} {% else %}
        <h2 class="mb-3 mx-4">События</h2> {% endcomment %}
    {% endif %}

    <!-- Вложенные директории -->
    <ul class="list-group mb-4">
        {% for directory in directories %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <!-- Название папки -->
                <a href="?directory={{ current_directory|default:'' }}/{{ directory.name|urlencode }}">{{ directory.name }}</a>

                <!-- Дата создания и кнопки управления -->
                <div class="date d-flex align-items-center">
                    <small class="me-3">{{ directory.creation_date }}</small>

                    {% if user.is_authenticated %}
                        <!--"Редактировать" -->
                        <button class="btn btn-sm btn-warning me-2" onclick="editFolder('{{ current_directory|default:'root' }}/{{ directory.name }}', this)" style="border: none; background: none; padding: 0;">
                        <img src="{% static 'icons/edit.png' %}" alt="Редактировать" style="width: 20px; height: 20px;">
                    </button>




                        <!--"Удалить" -->
                        <form onsubmit="event.preventDefault(); deleteFolder('{{ current_directory|default:'' }}/{{ directory.name }}', this)">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger" style="border: none; background: none; padding: 0;">
                                <img src="{% static 'icons/delete.png' %}" alt="Удалить" style="width: 20px; height: 20px;">
                            </button>
                        </form>

                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>

    <!-- Фотографии -->
    <div class="row g-3">
        {% for photo in photos %}
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 col-xxl-2">
        <div class="photo-card position-relative">
            <img src="{{ MEDIA_URL }}{{ current_directory|default:'' }}/{{ photo|urlencode }}" 
                 class="d-block w-100" 
                 alt="{{ photo }}" 
                 style="max-height: 200px; object-fit: cover;" 
                 data-bs-toggle="modal" 
                 data-bs-target="#photoCarouselModal"
                 onclick="showPhotoCarousel({{ forloop.counter0 }})">

            {% if user.is_authenticated %}
                <button class="btn btn-danger btn-sm delete-media-btn position-absolute top-0 end-0"
                        data-media="{{ current_directory|default:'' }}/{{ photo|urlencode }}">
                    ✖
                </button>
            {% endif %}
        </div>
    </div>
{% endfor %}

{% for video in videos %}
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 col-xxl-2">
        <div class="photo-card position-relative">
            <video class="d-block w-100" style="max-height: 200px; object-fit: cover;" 
                   data-bs-toggle="modal" 
                   data-bs-target="#photoCarouselModal"
                   onclick="showPhotoCarousel({{ forloop.counter0|add:photos|length }})"
                   muted>
                <source src="{{ MEDIA_URL }}{{ current_directory|default:'' }}/{{ video|urlencode }}" type="video/mp4">
                Ваш браузер не поддерживает видео.
            </video>

            {% if user.is_authenticated %}
                <button class="btn btn-danger btn-sm delete-media-btn position-absolute top-0 end-0"
                        data-media="{{ current_directory|default:'' }}/{{ video|urlencode }}">
                    ✖
                </button>
            {% endif %}
        </div>
    </div>
{% endfor %}

    </div>
    
    

    <!-- Модальное окно с каруселью -->
    <div class="modal fade" id="photoCarouselModal" tabindex="-1" aria-labelledby="photoCarouselLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="photoCarouselLabel">Просмотр файлов</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <div id="photoCarousel" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for photo in photos %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <img src="{{ MEDIA_URL }}{{ current_directory|default:'' }}/{{ photo|urlencode }}" 
                                         class="d-block w-100" 
                                         alt="{{ photo }}" 
                                         style="max-height: 80vh; object-fit: contain;">
                                </div>
                            {% endfor %}
                            
                            {% for video in videos %}
                                <div class="carousel-item {% if forloop.first and not photos %}active{% endif %}">
                                    <video controls class="d-block w-100" style="max-height: 80vh; object-fit: contain;">
                                        <source src="{{ MEDIA_URL }}{{ current_directory|default:'' }}/{{ video|urlencode }}" type="video/mp4">
                                        Ваш браузер не поддерживает видео.
                                    </video>
                                </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#photoCarousel" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Предыдущая</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#photoCarousel" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Следующая</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    

    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'urp/js/script.js' %}"></script>

</body>
</html>